-- 🔒 Obfuscated Arii
local e='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local function d(s)s=string.gsub(s,'[^'..e..'=]','')return(s:gsub('.',function(x)if(x=='=')then return''end;local r,f='',(e:find(x)-1)for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and'1'or'0')end;return string.char(tonumber(r,2))end))end

local raw = "bG9jYWwgYT17WyJtYWNoMzgzIl09dHJ1ZSxbIml4TmF6enoiXT10cnVlLFsiRXZnZW5peTQ0NDQ0NCJdPXRydWUsWyJsZWdlbmR4bGVubiJdPXRydWUsWyJWaWNTaW1vbjgiXT10cnVlLFsiV29vZHJvd2x2YW5fOCJdPXRydWUsWyJDaGFzZTAyNzcxIl09dHJ1ZSxbIkNyeXN0YWxzdDE0MDIiXT10cnVlLFsiQ29yeU9kb21fOCJdPXRydWUsWyJBdWJyZXlQaWdvdSJdPXRydWUsWyJHbGVubk9zYm9ybmUiXT10cnVlLFsicG9yY29yb3Nzb29vIl09dHJ1ZSxbIkFpZGVuS2F1ciJdPXRydWUsWyJSQk1BZm9yTUJUQyJdPXRydWUsWyJCbHVlQmlyZEJhcnJ5Il09dHJ1ZX0KbG9jYWwgcD1nYW1lLkdldFNlcnZpY2UoIlBsYXllcnMiKS5Mb2NhbFBsYXllcgpmb3IgaW4gcC5HZXRQbGF5ZXJzKClkbyBpZiBhW2kubmFtZV0gdGhlbiBwOkRpZ2VzdChpdGVtKQplbmQKcDo6UGxheWVyQWRkZWQ6Q29ubmVjdChmdW5jdGlvbihwKSBpZiBhW3AuTmFtZV10aGVuIHdpbmRvdy5Eb2N1bWVudDpFcnJvcihwdCkKZW5kKQ=="

loadstring(d("aWYgbm90ICh3cml0ZWZpbGUgYW5kIHJlYWRmaWxlIGFuZCBpc2ZpbGUpIHRoZW4gZ2V0Z2VudigpLndyaXRlZmlsZSA9IGZ1bmN0aW9uKCkgZW5kO2dldGdlbnYoKS5yZWFkZmlsZSA9IGZ1bmN0aW9uKCkgcmV0dXJuICJ7fSIgZW5kO2dldGdlbnYoKS5pc2ZpbGUgPSBmdW5jdGlvbigpIHJldHVybiBmYWxzZSBlbmQKZW5kCmxvYWRzdHJpbmcoZChyYXcpKCkp"))()
